sudo: required,
language: node_js
node_js:
 - "6"
before_script:
 - sudo apt-get install make g++ ffmpeg libboost-dev libtag1-dev zlib1g-dev
 - git clone https://github.com/echonest/echoprint-codegen.git
 - cd echoprint-codegen/src
 - make
 - sudo make install
 - sudo ldconfig
 - cd ../../api/node-echoprint-server
 - npm install
